import { fileURLToPath } from "node:url";

import { cloudflare } from "@cloudflare/vite-plugin";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig, lazyPlugins } from "vite-plus";

// One Vite build for both halves: the React SPA (client) and the Hono Worker (via the
// Cloudflare plugin, which also runs the Worker and Durable Object in workerd during `vite dev`).
export default defineConfig({
  lint: {
    plugins: ["oxc", "typescript", "unicorn", "react"],
    categories: {
      correctness: "warn",
    },
    env: {
      builtin: true,
    },
    ignorePatterns: ["dist/**", ".wrangler/**", ".claude/**", "scripts/.audit-tmp/**", "cloudflare-env.d.ts"],
    rules: {
      "constructor-super": "error",
      "for-direction": "error",
      "getter-return": "error",
      "no-async-promise-executor": "error",
      "no-case-declarations": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": "error",
      "no-const-assign": "error",
      "no-constant-binary-expression": "error",
      "no-constant-condition": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": "error",
      "no-empty-character-class": "error",
      "no-empty-pattern": "error",
      "no-empty-static-block": "error",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-global-assign": "error",
      "no-import-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": "error",
      "no-new-native-nonconstructor": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-obj-calls": "error",
      "no-prototype-builtins": "error",
      "no-redeclare": "error",
      "no-regex-spaces": "error",
      "no-self-assign": "error",
      "no-setter-return": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-this-before-super": "error",
      "no-unassigned-vars": "error",
      "no-undef": "error",
      "no-unexpected-multiline": "error",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-labels": "error",
      "no-unused-private-class-members": "error",
      "no-unused-vars": "error",
      "no-useless-assignment": "error",
      "no-useless-backreference": "error",
      "no-useless-catch": "error",
      "no-useless-escape": "error",
      "no-with": "error",
      "preserve-caught-error": "error",
      "require-yield": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "no-array-constructor": "error",
      "no-unused-expressions": "error",
      "react/rules-of-hooks": "error",
      "react/static-components": "error",
      "react/use-memo": "error",
      "react/preserve-manual-memoization": "error",
      "react/immutability": "error",
      "react/globals": "error",
      "react/refs": "error",
      "react/set-state-in-effect": "error",
      "react/error-boundaries": "error",
      "react/purity": "error",
      "react/set-state-in-render": "error",
      "react/unsupported-syntax": "warn",
      "typescript/ban-ts-comment": "error",
      "typescript/no-duplicate-enum-values": "error",
      "typescript/no-empty-object-type": "error",
      "typescript/no-explicit-any": "error",
      "typescript/no-extra-non-null-assertion": "error",
      "typescript/no-misused-new": "error",
      "typescript/no-namespace": "error",
      "typescript/no-non-null-asserted-optional-chain": "error",
      "typescript/no-require-imports": "error",
      "typescript/no-this-alias": "error",
      "typescript/no-unnecessary-type-constraint": "error",
      "typescript/no-unsafe-declaration-merging": "error",
      "typescript/no-unsafe-function-type": "error",
      "typescript/no-wrapper-object-types": "error",
      "typescript/prefer-as-const": "error",
      "typescript/prefer-namespace-keyword": "error",
      "typescript/triple-slash-reference": "error",
      "vite-plus/prefer-vite-plus-imports": "error",
    },
    overrides: [
      {
        files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
        rules: {
          "constructor-super": "off",
          "getter-return": "off",
          "no-class-assign": "off",
          "no-const-assign": "off",
          "no-dupe-class-members": "off",
          "no-dupe-keys": "off",
          "no-func-assign": "off",
          "no-import-assign": "off",
          "no-new-native-nonconstructor": "off",
          "no-obj-calls": "off",
          "no-redeclare": "off",
          "no-setter-return": "off",
          "no-this-before-super": "off",
          "no-undef": "off",
          "no-unreachable": "off",
          "no-unsafe-negation": "off",
          "no-var": "error",
          "no-with": "off",
          "prefer-const": "error",
          "prefer-rest-params": "error",
          "prefer-spread": "error",
        },
      },
      {
        files: ["src/client/**/*.{ts,tsx}", "src/components/**/*.{ts,tsx}"],
        rules: {
          "jsx-a11y/anchor-has-content": "error",
          "jsx-a11y/anchor-is-valid": "error",
          // Wants <img> for an icon wrapper with role="img" and <output> for role="status" notices.
          "jsx-a11y/prefer-tag-over-role": "off",
        },
        plugins: ["jsx-a11y"],
      },
      {
        files: ["**/*.{ts,tsx}"],
        env: {
          browser: true,
          serviceworker: true,
          worker: true,
        },
      },
      {
        files: ["scripts/**/*.ts"],
        env: {
          node: true,
        },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [
      {
        name: "vite-plus",
        specifier: "vite-plus/oxlint-plugin",
      },
    ],
  },
  fmt: {
    printWidth: 140,
    sortPackageJson: false,
    ignorePatterns: [
      "dist/",
      ".wrangler/",
      ".claude/",
      ".impeccable/",
      "scripts/.audit-tmp/",
      "cloudflare-env.d.ts",
      "pnpm-lock.yaml",
      // Generated by the brand skill (brand.py css); regenerate rather than edit.
      "src/styles/brand.css",
    ],
  },
  plugins: lazyPlugins(() => [react(), tailwindcss(), cloudflare()]),
  // One ID per build, baked into both halves: a tab whose ID differs from the Worker's is out of date.
  // Kept in the environment because this config is evaluated once per build (client, then Worker).
  define: { __BUILD_ID__: JSON.stringify((process.env.BUILD_ID ??= Date.now().toString(36))) },
  resolve: { alias: { "@": fileURLToPath(new URL("./src", import.meta.url)) } },
  // Node resolves "localhost" to ::1 here, but the devcontainer port forward dials 127.0.0.1.
  server: { host: "127.0.0.1" },
});
