// Worker entry: auth, the GitHub webhook and the live socket are handled here, before Next.
// Everything else goes to the OpenNext handler (built into .open-next/ by `opennextjs-cloudflare build`).

// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- see below
// @ts-ignore: generated by the OpenNext build (absent until the first build, so not @ts-expect-error)
import { default as nextHandler } from "./.open-next/worker.js";
import { handleAuth, sessionLogin, unauthenticated } from "./src/edge/auth";
import { verifyWebhook } from "./src/edge/crypto";
import { hubStub, type EdgeEnv } from "./src/edge/env";

export { Hub } from "./src/edge/hub";

const WEBHOOK_PATH = "/api/github/webhook";

export default {
  async fetch(req, env, ctx) {
    const { pathname } = new URL(req.url);
    const hub = hubStub(env);

    // Public, but only GitHub can sign it.
    if (pathname === WEBHOOK_PATH) {
      if (req.method !== "POST") return new Response("Method Not Allowed", { status: 405 });
      const body = await req.text();
      if (!(await verifyWebhook(env.GITHUB_WEBHOOK_SECRET, body, req.headers.get("X-Hub-Signature-256")))) {
        return new Response("Bad signature", { status: 401 });
      }
      const event = req.headers.get("X-GitHub-Event") ?? "";
      const delivery = req.headers.get("X-GitHub-Delivery") ?? "";
      // Ack immediately; GitHub times out deliveries after 10s.
      ctx.waitUntil(hub.webhook(delivery, event, JSON.parse(body)));
      return new Response(null, { status: 202 });
    }

    const auth = await handleAuth(req, env, {
      saveTokens: (t) => hub.saveTokens(t),
      signOut: () => hub.signOut(),
    });
    if (auth) return auth;

    if (!(await sessionLogin(req, env))) return unauthenticated(req);

    if (pathname === "/api/live") return hub.fetch(req);

    return nextHandler.fetch(req, env, ctx);
  },
} satisfies ExportedHandler<EdgeEnv>;
